name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.get-latest-tag.outputs.tag }}"

          mkdir -p sticky-notes-plugin
          cp main.js manifest.json styles.css sticky-notes-plugin/

          zip -r sticky-notes-plugin.zip sticky-notes-plugin
          tar -czvf sticky-notes-plugin.tar.gz sticky-notes-plugin

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            sticky-notes-plugin.zip \
            sticky-notes-plugin.tar.gz \
            main.js \
            manifest.json \
            styles.css